#!/bin/sh
#
# @author Andrea Tassotti
#
set -e

case "$1" in
	configure)
		echo "postinst called with configure" >&2
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
